# Project identification
sonar.projectKey=AI-Disease-Predictor
sonar.projectName=AI Disease Prediction System
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Integration with JaCoCo (Coverage)
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Language
sonar.language=java
sonar.sourceEncoding=UTF-8